### ISSUE TITLE
[Bug] Dorion Settings aren't present

### ISSUE THREAD

**Issue by Niklas20114552** [SpikeHD/Dorion#152] opened 2023-11-10 14:42 UTC
**Describe the bug**
There are no Dorion Settings visible in the Discord Settings.

**To Reproduce**
1. Start Dorion
2. Open Settings

**Expected behavior**
I would expect to see the settings here as described in the README.

**Screenshots**
![Screenshot_20231110_153827](https://github.com/SpikeHD/Dorion/assets/83753407/467a8eed-c6a3-4f49-ace4-00761fe4c987)
(sorry it's german)

**System Info (please complete the following information):**
 - OS: Arch Linux
 - Any other relevant info: Dorion was installed through the AUR

**Comment by haxerman123** [comment] 2023-11-10 15:00
try manually killing the dorion process and starting dorion again, if that doesn't work change the language from german to english

**Comment by Niklas20114552** [comment] 2023-11-10 15:11
Unfortunately neither of these suggestions work. I restarted Dorion now 7-times with English-US as language.

**Comment by haxerman123** [comment] 2023-11-10 15:16
> Unfortunately neither of these suggestions work. I restarted Dorion now 7-times with English-US as language.

weird. does it inject anything on startup? does it day anything?

**Comment by Niklas20114552** [comment] 2023-11-10 15:20
I don't now, but here is the log:
https://gist.github.com/Niklas20114552/6c5b5bb3652ac35f75f07928733d7564

**Comment by haxerman123** [comment] 2023-11-10 15:22
seems like a incompatibility eith dorion and arch linux

**Comment by Niklas20114552** [comment] 2023-11-10 15:23
so nothing that can be easily fixed without being a developer?

**Comment by haxerman123** [comment] 2023-11-10 15:24
no idea, your best luck of it working is on windows and maybe some other distros of linux or mac os

**Comment by haxerman123** [comment] 2023-11-10 15:25
also were there settings before it stopped working?

**Comment by Niklas20114552** [comment] 2023-11-10 15:25
no there were never settings

**Comment by Niklas20114552** [comment] 2023-11-10 15:26
okay and thank you for your trying to help!

**Comment by SpikeHD** [comment] 2023-11-10 18:02
This should be a relatively simple fix where Dorion will have to use a fallback script instead. Should be something I can get done for the next release 👍

**Comment by SpikeHD** [comment] 2023-11-10 18:17
Also, just curious, does `$HOME/.local/share/dorion` contain a folder called `injection` with a single file within called `browser.js`?

**Comment by Niklas20114552** [comment] 2023-11-10 19:02
Nope. That folder does not exists.

**Comment by piotr25691** [comment] 2023-11-10 19:23
possible duplicate of #138? try refreshing to get them to appear

**Comment by SpikeHD** [comment] 2023-11-10 19:24
No, this is different

**Comment by Niklas20114552** [comment] 2023-11-11 08:58
Now i tried to install dorion on Ubuntu Unity and the exact same bug also occurred. Here's the [log](https://gist.github.com/Niklas20114552/c33e8d4385d8e89ef8598825f6f7806c). And there is also no ```injection``` folder

**Comment by SpikeHD** [comment] 2023-11-11 09:11
@Niklas20114552 you can try a `.deb` from [GitHub Actions](https://github.com/SpikeHD/Dorion/actions/workflows/build.yml), which should have the fallback fix. Lemme know if that works for you!

**Comment by Niklas20114552** [comment] 2023-11-11 09:24
The latest Build worked.

**Comment by SpikeHD** [comment] 2023-11-11 09:30
Glad to hear it! I'll close this now since that will be fixed/available in the next release.

**Closed by SpikeHD** 2023-11-11 09:30 UTC
Labels: bug
