### ISSUE TITLE
[Bug] Can't set `System.AppUserModel.ID` install warning

### ISSUE THREAD

**Issue by headquarter8302** [SpikeHD/Dorion#255] opened 2024-09-20 23:43 UTC
**Describe the bug**
While installing Dorion, this popup appears after it has done installing via MSI, before showing the exit confirmation screen.

**To Reproduce**
1. Install Dorion.
2. Wait for the installation to succeed.
3. Get error, the modal is dismissible and nonfatal.

**Expected behavior**
No errors appearing.

**Screenshots**
![image](https://github.com/user-attachments/assets/67ef3168-e94f-46e9-9846-82233bbb5815)

**System Info (please complete the following information):**
 - OS: Windows 11 Build 22621
 - Version: v6.0.1

**Additional context**
N/a

**Comment by SpikeHD** [comment] 2024-09-20 23:46
Does this happen multiple times? Was Dorion open shortly before running the installer? Or similarly, did you close Dorion *after* opening the installer? Because I have experienced this plenty of times while testing install files and iirc it's not really anything to worry about

**Comment by headquarter8302** [comment] 2024-09-20 23:47
I've fully closed and uninstalled Dorion and its leftover files before running the installer, this still occurs, multiple times

**Comment by SpikeHD** [comment] 2024-09-20 23:51
I've tried to reproduce a few times and haven't been able to. Every time this *does* happen to me while testing, it affects nothing and the install works fine, so I'm going to close this.

**Closed by SpikeHD** 2024-09-20 23:51 UTC
Labels: bug
