### ISSUE TITLE
[Feature Request] Wayland Support

### ISSUE THREAD

**Issue by nyabinary** [SpikeHD/Dorion#46] opened 2023-07-16 16:47 UTC
**Is your feature request related to a problem? Please describe.**
- [ ] Wayland Support
- [ ] Wayland Screensharing Support
- [ ] Pipewire Support (To make Audio Screensharing Work)

**Describe the solution you'd like**
Implementation of these features (Armcord is currently working on this as well)
Make Wayland work natively on Dorion instead of running it through Xwayland.

**Comment by samolego** [comment] 2024-08-01 20:42
This'd be great to have, especially since some desktops (kde plasma cough cough) is now using wayland by default :)

**Comment by samolego** [comment] 2024-08-01 20:44
Currently it crashes on build:
```
rror: failed to run custom build command for `x11 v2.21.0`

Caused by:
  process didn't exit successfully: `/home/samoh/Downloads/Dorion/src-tauri/target/release/build/x11-f91ec7c39c4e5d81/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=X11_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=X11_STATIC
  cargo:rerun-if-env-changed=X11_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at /home/samoh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/x11-2.21.0/build.rs:42:14:
  called `Result::unwrap()` on an `Err` value: 
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags x11 x11 >= 1.4.99.1

  The system library `x11` required by crate `x11` was not found.
  The file `x11.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `x11.pc`.

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
       Error failed to build app: failed to build app
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by SpikeHD** [comment] 2024-08-01 21:45
@samolego  Out of purely curiosity, can you try building the `next` branch? That's on Tauri v2 and may not hard-require X11 anymore. Keep in mind it won't work properly, I'd just like to know if this issue will be closed by that move

**Comment by samolego** [comment] 2024-08-02 07:16
Sadly still fails with same X11 error :(.

**Comment by SpikeHD** [comment] 2024-08-02 15:50
Mkay, it should still work under Wayland just fine but you'll need to install X11 just for the build dependency I guess (or you can just download a release of course)

**Comment by samolego** [comment] 2024-08-02 19:06
Ah, nice to know that!

Yeah, might just use the released tarball :)

**Comment by SpikeHD** [comment] 2024-08-09 19:05
Tested and confirmed that the Dorion window runs with native Wayland (not `xwayland`) using both `xeyes` and `xwininfo` to test in a Wayland session (ty [Arch Wiki](https://wiki.archlinux.org/title/Wayland)). Honestly, I'm pretty sure this has been the case for a long time already, I just never tested it myself until now :P

I'm gonna close this since screenshare/audio/etc. are separate issues that cannot even really be tackled until WebKitGTK ships with WebRTC support (and even then, I only have so much control over it, so I don't know how feasible these even are)

**Closed by SpikeHD** 2024-08-09 19:05 UTC
Labels: enhancement, future goal
