### ISSUE TITLE
[Bug] Standard Icon doesn't change to show notifications

### ISSUE THREAD

**Issue by Mason-17** [SpikeHD/Dorion#78] opened 2023-08-22 06:19 UTC
**Describe the bug**
When using the standard installation, and having the app open, the icon in the taskbar doesn't have the numbers appear.

**To Reproduce**
1. Use the app

**Expected behavior**
When pinged, the icon should change to reflect it.

**Screenshots**

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v0.9.1
 - Any other relevant info: 

**Additional context**
Oddly enough, a workaround exists by not having the app pinned to the taskbar. In fact, you can customize the icon and everything (potential feature?). However, pinning the app will not show the numbers.

**Comment by SpikeHD** [comment] 2023-08-22 06:26
Duplicate of #27 and #68

**Closed by SpikeHD** 2023-08-22 06:26 UTC
Labels: bug
