### ISSUE TITLE
[Bug] Window is briefly at a small size before restoring to the size it should be

### ISSUE THREAD

**Issue by Poopooracoocoo** [SpikeHD/Dorion#89] opened 2023-09-08 06:54 UTC
**Describe the bug**
Window is briefly at a small size before restoring to the size it should be

**To Reproduce**
Open Dorion

**Expected behavior**
Dorion does not resize itself

**Screenshots**

**System Info (please complete the following information):**
 - OS: Windows 10 22H2 OS Build 19045.3324
 - Version: 1.1.0
 - Any other relevant info: 

**Additional context**
https://github.com/modrinth/theseus/issues/374 may help

**Comment by Napoleon-x** [comment] 2023-09-09 18:43
This issue is a clone of #87

**Comment by Poopooracoocoo** [comment] 2023-09-09 18:51
Not the same issue as #87 from what I can tell

**Comment by i3sey** [comment] 2023-09-10 04:31
The problem is that the Dorion window doesn't remember the size. After each launch you have to manually increase window size.

**Comment by Poopooracoocoo** [comment] 2023-09-10 05:03
IIRC, Dorion already uses the window-state plugin so it _should_ work. Something must be going wrong. It's worth looking at how [Modrinth](https://github.com/modrinth/theseus/pull/381/files#diff-a052d3bcb4186214f195bf5fa51ce2603efbc2717d52c9f40a6e99c4b1499754) fixed this issue with their app.

**Comment by SpikeHD** [comment] 2023-09-10 05:14
"Misc bugs 4" how descriptive 🥴

**Comment by Napoleon-x** [comment] 2023-09-11 15:43
> Not the same issue as #87 from what I can tell

My bad the wording confused me but I see now you meant the actual window itself 👍

**Comment by SpikeHD** [comment] 2023-10-09 20:36
Should be fixed as of 109c49d

**Closed by SpikeHD** 2023-10-09 20:36 UTC
Labels: bug

**Comment by plutonium-239** [comment] 2023-11-29 05:06
Is this in the latest build? 
If so, I am still facing the same issue (installed yesterday)
Are there any logs for this that I can share?

**Comment by SpikeHD** [comment] 2023-11-29 05:46
The changes are included, yes, maybe I broke them after the commit, idk. All you'd need to is provide the same info asked for in the issue template.

**Comment by plutonium-239** [comment] 2023-11-29 06:02
Sure
OS: Windows 10 22H2 OS (Build 19045.3693)
Version: 2.2.1

**Comment by plutonium-239** [comment] 2023-12-04 10:33
Hey @SpikeHD, did you figure out why this was happening?

**Comment by Temanor** [comment] 2023-12-04 12:14
Still appears in the latest actions build :(

**Comment by plutonium-239** [comment] 2023-12-08 10:03
It doesn't appear to be happening in the latest release (2.3.0) [posted a day after @Temanor's comment]
