### ISSUE TITLE
[Bug] Window breaks

### ISSUE THREAD

**Issue by Scrapper1824** [SpikeHD/Dorion#102] opened 2023-09-24 03:04 UTC
**Describe the bug**
the window brakes

**To Reproduce**
minimize the window and maximize it. it might take a couple trys

**Expected behavior**
broken window

**Screenshots**
![Screenshot (49)](https://github.com/SpikeHD/Dorion/assets/72410525/0e1d2e4c-7217-46a3-8092-b2f37a0950c3)

**System Info (please complete the following information):**
 - OS: [Windows 11]
 - Version: [22621.2283]

**Comment by SpikeHD** [comment] 2023-09-24 03:27
Duplicate of #87

**Closed by SpikeHD** 2023-09-24 03:27 UTC
Labels: bug
