### ISSUE TITLE
[Feature Request] Auto update

### ISSUE THREAD

**Issue by Dysta** [SpikeHD/Dorion#98] opened 2023-09-17 13:57 UTC
**Is your feature request related to a problem? Please describe.**
Actually, on a new version of Dorion we have a tiny popup telling us it. It should be good to have a self update or a system like Discord.  It will avoid this insanity in my download folder 
![image](https://github.com/SpikeHD/Dorion/assets/25008828/758d793f-a217-4d65-8dea-b3309805f658)

**Describe the solution you'd like**
A self update system in Tauri. Already discuss on Discord.
Maybe implement this https://tauri.app/v1/guides/distribution/updater/

**Describe alternatives you've considered**
-

**Additional context**
Love u <3

**Comment by SpikeHD** [comment] 2023-09-17 18:05
Duplicate of #73

**Closed by SpikeHD** 2023-09-17 18:05 UTC
Labels: enhancement
