### ISSUE TITLE
[Bug] Vertical scrollbar in Spotify embed

### ISSUE THREAD

**Issue by piotr25691** [SpikeHD/Dorion#247] opened 2024-07-12 15:11 UTC
**Describe the bug**
Describe the problem here.

A vertical scrollbar appears in the embed when sending a Spotify link.

**To Reproduce**

1. Go to any chat
2. Send a Spotify link: https://open.spotify.com/track/14cxhUvJbuo61Hb1wYQbP7?si=e19c5aa786734286

**Expected behavior**
Describe what should be expected here.

No scrollbar should be present.
![Example Screenshot](https://github.com/user-attachments/assets/e8960d21-2bd3-47ee-a388-406b0708b4d1)

**Screenshots**

![image](https://github.com/user-attachments/assets/8207eda9-f79f-4504-b33a-4c2b792c60f7)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v5.0.1
 - Any other relevant info: None

**Additional context**

I have nothing to say, please verify.

**Comment by SpikeHD** [comment] 2024-07-14 03:34
Interestingly, this does not happen for me (though, I am on Windows 10)

![image](https://github.com/user-attachments/assets/42cd934e-7f89-4e2f-ac1f-83786ba94291)

I assume you aren't using any themes?

**Comment by piotr25691** [comment] 2024-07-14 07:43
> Interestingly, this does not happen for me (though, I am on Windows 10)
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/42cd934e-7f89-4e2f-ac1f-83786ba94291)
> 
> 
> 
> I assume you aren't using any themes?

I have turned them off and this stayed.

**Comment by SpikeHD** [comment] 2024-09-21 01:36
Is this still happening?

**Comment by piotr25691** [comment] 2024-09-21 06:25
I have no idea, I left Dorion again.

**Comment by SpikeHD** [comment] 2024-09-21 06:48
No worries, I'll close this for now since I've never been able to reproduce. If someone else comments that it is still a problem I will reopen

**Closed by SpikeHD** 2024-09-21 06:48 UTC
Labels: bug
